# Bronze - Genres Data

## Setup Environment and Prepare data

In [1]:
from letterboxd_data_pipeline.load_data import load_files_from_layer

bronze_df = load_files_from_layer(layer="bronze", file_list=["genres.parquet"])
bronze_genres_df = bronze_df["genres"]

Start loading data...
Loading: data/bronze/genres.parquet
Done!
Finish loading.

## Simple Explore

In [2]:
bronze_genres_df.describe(include="all")

             id    genre
count   1046849  1046849
unique   676491       19
top     1452952    Drama
freq         17   232201

In [3]:
bronze_genres_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1046849 entries, 0 to 1046848
Data columns (total 2 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   id      1046849 non-null  object
 1   genre   1046849 non-null  object
dtypes: object(2)
memory usage: 16.0+ MB

## Number of NA

In [4]:
bronze_genres_df.isna().sum()

id       0
genre    0
dtype: int64

## Top 10 Genre

In [5]:
bronze_genres_df.groupby("genre").agg(total=("id","count")).sort_values("total", ascending=False).head(10)

              total
genre
Drama        232201
Documentary  163890
Comedy       140636
Animation     58708
Horror        53870
Romance       51549
Thriller      46726
Music         44105
Action        41695
Crime         35507

## Movie with most Genre

In [6]:
most_flavored_movies_df = bronze_genres_df.copy(True)

grouped_source_df = most_flavored_movies_df.groupby(by=["id"])

most_flavored_movies_df["genre_count"] = grouped_source_df["id"].transform(len)

most_flavored_movies_df = most_flavored_movies_df[
    ["id", "genre", "genre_count"]
].sort_values(["genre_count", "genre"], ascending=[False, True])

most_flavored_movies_df

              id        genre  genre_count
653695   1452952       Action           17
653696   1452952    Adventure           17
653687   1452952       Comedy           17
653688   1452952        Crime           17
653689   1452952  Documentary           17
...          ...          ...          ...
1042897  1935179      Western            1
1043091  1935400      Western            1
1043731  1936242      Western            1
1043917  1936599      Western            1
1045330  1939638      Western            1

[1046849 rows x 3 columns]