# Bronze - Countries Data

## Setup Environment and Prepare data

In [ ]:
from letterboxd_data_pipeline.load_data import load_files_from_layer

bronze_df = load_files_from_layer(layer="bronze", file_list=["countries"])
bronze_countries_df = bronze_df["countries"]

Start loading data...
Loading: ../data/bronze/countries
Done!
Finish loading.

## Simple Explore

In [2]:
bronze_countries_df.describe(include="all")

                  id country
count   6.934760e+05  693476
unique           NaN     247
top              NaN     USA
freq             NaN  174489
mean    1.388132e+06     NaN
std     2.691242e+05     NaN
min     1.000001e+06     NaN
25%     1.148019e+06     NaN
50%     1.352616e+06     NaN
75%     1.606962e+06     NaN
max     1.941597e+06     NaN

In [3]:
bronze_countries_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 693476 entries, 0 to 693475
Data columns (total 2 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   id       693476 non-null  int64
 1   country  693476 non-null  object
dtypes: int64(1), object(1)
memory usage: 10.6+ MB

In [4]:
bronze_countries_df.head(10)

        id      country
0  1000001           UK
1  1000001          USA
2  1000002  South Korea
3  1000003          USA
4  1000004      Germany
5  1000004          USA
6  1000005    Hong Kong
7  1000005          USA
8  1000006           UK
9  1000006          USA

## Number of NA

In [ ]:
bronze_countries_df.isna().sum()

id         0
country    0
dtype: int64

## Movie with most countries

In [7]:
bronze_countries_df.groupby("id").agg(total_countries=("country", "count")).sort_values(by="total_countries",ascending=False)

         total_countries
id
1188661               30
1106357               26
1116437               26
1181951               25
1038152               25
...                  ...
1260690                1
1260691                1
1260692                1
1260693                1
1260682                1

[617192 rows x 1 columns]

In [8]:
bronze_countries_df[bronze_countries_df["id"] == 1188661]

             id                           country
212032  1188661                            Angola
212033  1188661                             Benin
212034  1188661                          Botswana
212035  1188661                          Cameroon
212036  1188661          Central African Republic
212037  1188661                              Chad
212038  1188661                             China
212039  1188661      Democratic Republic of Congo
212040  1188661                       Ivory Coast
212041  1188661                            France
212042  1188661                             Gabon
212043  1188661                         Hong Kong
212044  1188661                             India
212045  1188661                            Israel
212046  1188661                             Italy
212047  1188661                             Kenya
212048  1188661  Lao People's Democratic Republic
212049  1188661                           Myanmar
212050  1188661                       Philippines
212051  1188661                Russian Federation
212052  1188661                           Senegal
212053  1188661                      South Africa
212054  1188661                         Sri Lanka
212055  1188661       United Republic of Tanzania
212056  1188661                          Thailand
212057  1188661                              Togo
212058  1188661                                UK
212059  1188661                               USA
212060  1188661                            Zambia
212061  1188661                          Zimbabwe