# Bronze - Curious Data

Curious data and probable easter eggs that is worth mentioning.

## Setup Environment and Prepare data

In [ ]:
from letterboxd_data_pipeline.load_data import load_files_from_layer
from letterboxd_data_pipeline.explore_data.explore_data import is_possible_na

bronze_df = load_files_from_layer(
    layer="bronze",
    file_list=[
        "actors.parquet",
        "movies.parquet",
        "countries.parquet",
        "crew.parquet",
        "releases.parquet",
    ],
)
actors_df = bronze_df["actors"].copy(True)
movies_df = bronze_df["movies"].copy(True)
countries_df = bronze_df["countries"].copy(True)
crews_df = bronze_df["crew"].copy(True)
releases_df = bronze_df["releases"]

Start loading data...
Loading: data/bronze/actors.parquet
Done!
Loading: data/bronze/movies.parquet
Done!
Loading: data/bronze/countries.parquet
Done!
Loading: data/bronze/crew.parquet
Done!
Loading: data/bronze/releases.parquet
Done!
Finish loading.

## Curious Actor and Movie Details

In [2]:
curious_df = actors_df.query("role == 'A Letterboxd User'")

curious_id = curious_df["id"].iloc[0]

curious_df

              id name               role
5792614  1938925   Na  A Letterboxd User

In [3]:
curious_df = actors_df.query("role == 'A Letterboxd User'")

curious_id = curious_df["id"].iloc[0]

curious_df

              id name               role
5792614  1938925   Na  A Letterboxd User

In [4]:
curious_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1 entries, 5792614 to 5792614
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      1 non-null      object
 1   name    1 non-null      object
 2   role    1 non-null      object
dtypes: object(3)
memory usage: 32.0+ bytes

### From which Movie

In [5]:
movies_df.query(f"id == {curious_id}")

details_df = curious_df.join(movies_df.set_index("id"), lsuffix="_actor", how="inner", on="id")

details_df

,id,name_actor,role,name,date,tagline,description,minute,rating
5792614,1938925,Na,A Letterboxd User,My Lie In January,None,None,Sooner or later a man who wears two faces forg...,8,None

In [6]:
details_df["description"].iloc[0]

'Sooner or later a man who wears two faces forgets which one is real'

### Movie Crew

In [7]:
crews_df.query(f"id == {curious_id}")

Empty DataFrame
Columns: [id, role, name]
Index: []

### Release date

In [8]:
releases_df.query(f"id == {curious_id}")

Empty DataFrame
Columns: [id, country, date, type, rating]
Index: []

## Actor name which is possible NA

In [9]:
actor_na_df = actors_df[is_possible_na(actors_df["name"])]

actor_na_df

              id name               role
5652329  1860568   Na               None
5792614  1938925   Na  A Letterboxd User

### From which movie and country

In [10]:
actor_na_df.join(movies_df.set_index("id"), lsuffix="_actor", on="id").join(
    countries_df.set_index("id"), on="id", rsuffix="_country"
)

,id,name_actor,role,name,date,tagline,description,minute,rating,country
5652329,1860568,Na,None,Two Brothers,2021,None,"Every September 27, Julio Valverde and his fam...",32,None,Brazil
5792614,1938925,Na,A Letterboxd User,My Lie In January,None,None,Sooner or later a man who wears two faces forg...,8,None,NaN

## Movie "none"

In [11]:
movie_id_none = 1770935

movie_none_df = movies_df.query(f"id == {movie_id_none}")
movie_none_df

Empty DataFrame
Columns: [id, name, date, tagline, description, minute, rating]
Index: []

In [12]:
details_none_df = movie_none_df.join(crews_df.set_index("id"), lsuffix="_actor", how="inner", on="id")

details_none_df

Empty DataFrame
Columns: [id, name_actor, date, tagline, description, minute, rating, role, name]
Index: []